admin:
    backendroles:
        - admin
    users:
        - elastic

kibana_user:
    backendroles:
        - kibana_user
    users:
        - kibana

search:
    backendroles:
        - search
    users:
        - frontend

sg_anonymous:
  backendroles:
    - sg_anonymous_backendrole
    - search
